### ISSUE TITLE
Question on bosh release for firehose-to-syslog

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry-community/firehose-to-syslog#168]
Dear Contributors/members,

Do we have a bosh release to deploy this component on a VM or this should be deployed only as an application in cloud foundry ?

Thanks
Naresh

**Comment by shinji62** [comment]
Use, to have one,  but you can use the job https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/tree/develop/jobs/ingestor_cloudfoundry-firehose from logsearch bosh release

**Comment by making** [comment]
@nsharmacovs 

This works for me.

``` yaml
releases:
- name: logsearch-for-cloudfoundry
  version: 206.0.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/logsearch-for-cloudfoundry?v=206.0.0
  sha1: 574720bed4d453ed4153f48d5244e2b4fde16354

# ...

instance_groups:
- name: firehose-to-syslog
  # ...
  jobs:
  - name: ingestor_cloudfoundry-firehose
    release: logsearch-for-cloudfoundry
    properties:
      syslog:
        host: ((syslog_host))
        port: ((syslog_port))
      cloudfoundry:
        api_endpoint: https://api.((system_domain))
        doppler_endpoint: wss://doppler.((system_domain)):((doppler_port))
        skip_ssl_validation: true
        firehose_events:
        - LogMessage
        firehose_subscription_id: ((firehose_subscription_id))
        firehose_client_id: ((firehose_client_id))
        firehose_client_secret: ((firehose_client_secret))
        firehose_cc_pull_interval: 0
      create-uaa-client:
        cloudfoundry:
          system_domain: ((system_domain))
          uaa_admin_client_id: ((uaa_admin_client_id))
          uaa_admin_client_secret: ((uaa_admin_client_secret))
```
