### ISSUE TITLE
invalid_token","error_description":"Invalid refresh token (expired)

### ISSUE THREAD

**Issue by madhuchiluka** [cloudfoundry-community/firehose-to-syslog#68]
We have seen the error messages in the logs of firehose-nozzle application until we restart the application. Until the restart, it stopped sending logs to syslog servers. It looks like it is failing to re-authenticate with uaa server and get a new token. 

Logs:

ERR Response: {"error":"invalid_token","error_description":"Invalid refresh token (expired): eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxMjM3YzEwZi05YmY0LTRmYzMtYjcyYS05NzY2YjU5OTViYmItciIsInN1YiI6Ijc0NmVmN2JmLTRmYWItNGI1NC05MTE4LTkyMmI5ZWYzZjMxNiIsInNjb3BlIjpbIm9wZW5pZ
CIsInNjaW0ucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIuYWRtaW4iLCJ1YWEudXNlciIsImNsb3VkX2NvbnRyb2xsZXIucmVhZCIsInBhc3N3b3JkLndyaXRlIiwiY2xvdWRfY29udHJvbGxlci53cml0ZSIsImRvcHBsZXIuZmlyZWhvc2UiXSwiaWF0IjoxNDUwMjk4OTI0LCJleHAiOjE0NTE1MDg1MjQsImNpZCI6ImNmIiwiY2xpZW50X2lkIjoiY2YiLCJpc3MiOiJodHRwczovL3VhYS5zY3Axc3lzc
GRjMS5zY2h3YWIuY29tL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcl9uYW1lIjoic3ZjLnNjcGZpcmVob3NlX3Byb2QiLCJvcmlnaW4iOiJsZGFwIiwidXNlcl9pZCI6Ijc0NmVmN2JmLTRmYWItNGI1NC05MTE4LTkyMmI5ZWYzZjMxNiIsInJldl9zaWciOiJlNmI1ZTg4ZCIsImF1ZCI6WyJjZiIsIm9wZW5pZCIsInNjaW0iLCJjbG91ZF9jb250c
m9sbGVyIiwidWFhIiwicGFzc3dvcmQiLCJkb3BwbGVyIl19.YrtlOCCU-iWUSMQmJKaiRV-P1P4sSpKbz0PCZd-jrxqR0_xrmeSW66JEb6-e0yNgV9NVNjEOnEZzijmlO1-J5KSzB8GH-qyrOU3Uz_SAXqBjH_epv42cdcOCmgEo-T8o4MS0A_BUcvh39NQOFaFTInvkteW8ulOqN2HhkHgjsf8xKrtvhNKD4c8H100YQQT0siWBfCk_rOCkHayXqbckOX5XtuHyGsXWorJ8ajWO0-q3P4fZI4nwp0m330-K
qRrtARVWs98xhujUxV78vtuTFSB1i7CKzErCfK0xILsLC4jLeWd0Sv6A4ajYIQXsl0_E8zGSMMyd68MXwhLPkWKRLQ expired at Wed Dec 30 20:48:44 UTC 2015"}

**Comment by shinji62** [comment]
Please which version of firehose to syslog are you using ?

**Comment by madhuchiluka** [comment]
This is what we have deployed
schwab branch: https://github.com/malston/firehose-to-syslog/tree/schwab

**Comment by madhuchiluka** [comment]
not sure what version was that

**Comment by deepwright** [comment]
We are also seeing the same error today. We had to restart the firehose app to fix the authentication issue.

version = "1.2.0 - 1cdb840"

Logs we saw in Firehose:

2016-01-25T23:10:50.000+00:00 [App/0] ERR 2016/01/25 23:10:50 Error requesting apps Get https://api.*.*.*.io/v2/apps?inline-relations-depth=2: oauth2: cannot fetch token: 401 Unauthorized
2016-01-25T23:11:50.000+00:00 [App/0] ERR Response: {"error":"invalid_token","error_description":"Invalid refresh token (password changed): *************************************************************"}
2016-01-25T23:11:50.000+00:00 [App/0] ERR [2016-01-25 23:11:50.790796839 +0000 UTC] Exception occurred! Message: Recovered in caching.GetAllApp() Details: runtime error: invalid memory address or nil pointer dereference

Please assist as we need to know how we can avoid this in future, as we will miss those logs if not catched due to this error.

**Comment by shinji62** [comment]
```"error":"invalid_token","error_description":"Invalid refresh token (password changed)```
Seems the password of the user use by the nozzle have been change. Did you change it ?

**Comment by shinji62** [comment]
@madhuchiluka Can you provide the uaa / login server logs ? Need to understand what is going on.

**Comment by madhuchiluka** [comment]
Is there any secure FTP server I can upload logs into? plus log file is larger than 10MB
I don't see any issues with the user. 
I'll check with my teammate to see if we can deploy master one. we wouldn't able to get the error right away, it usually taking few weeks to reoccur.

**Comment by shinji62** [comment]
Just put somewhere like google drive or something like that.

**Comment by madhuchiluka** [comment]
I have sent logs to notification@github.com through Schwab secure messaging system. Please let me know if you not get it. I can try send it to your email directly if you can provide that

**Comment by shinji62** [comment]
You can send here gwenn.etourneau@gmail.com

**Comment by shinji62** [comment]
How did you create the user "svc.scpfirehose_prod" ??
authorized-grant-types ??

**Comment by madhuchiluka** [comment]
I have sent out logs to your gmail account. you might have to register or something to view the logs. 

We integrated pcf with LDAP. we had to login to pcf instance with svc.scpfirehose_prod to register that account in uaa database then we provided following scopes to that account 
scim.read
cloud_controller.admin
doppler.firehose
and other default ones.

**Comment by shinji62** [comment]
That the scope, I want the grants_type like ```$uaac clients ```
```
 admin
    scope: uaa.none
    resource_ids: none
    authorized_grant_types: client_credentials
    autoapprove:
    action: none
    authorities: clients.read password.write clients.secret clients.write uaa.admin scim.write scim.read
    lastmodified: 1452911318522
  cc_routing
    scope: uaa.none
    resource_ids: none
    authorized_grant_types: authorization_code refresh_token
    autoapprove:
    action: none
    authorities: uaa.none
    lastmodified: 1452911318087
  cf
    scope: cloud_controller.admin cloud_controller.read cloud_controller.write doppler.firehose openid password.write
        routing.router_groups.read scim.read scim.write uaa.user
    resource_ids: none
    authorized_grant_types: implicit password refresh_token
    autoapprove: true
    access_token_validity: 600
    refresh_token_validity: 2592000
    action: none
    authorities: uaa.none
    lastmodified: 1452911318869
```
